name: Testing events
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/workflows'

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Echoing Hello world
              run: echo "Hello World from Simon Shah"
